version: '3.1'

services:
  db:
    image: docker.io/postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  adminer:
    image: docker.io/adminer
    ports:
      - 8080:8080
